README.markdown
files/providers/wls_authentication_provider/create.py.erb
files/providers/wls_datasource/create.py.erb
files/providers/wls_datasource/modify.py.erb
files/providers/wls_identity_asserter/create.py.erb
files/providers/wls_identity_asserter/destroy.py.erb
files/providers/wls_identity_asserter/index.py.erb
files/providers/wls_identity_asserter/modify.py.erb
lib/puppet/provider/wls_identity_asserter/simple.rb
lib/puppet/type/wls_datasource.rb
lib/puppet/type/wls_datasource/xaproperties.rb
lib/puppet/type/wls_identity_asserter.rb
lib/puppet/type/wls_identity_asserter/activetypes.rb
lib/puppet/type/wls_identity_asserter/attributes.rb
lib/puppet/type/wls_identity_asserter/attributesvalues.rb
lib/puppet/type/wls_identity_asserter/authentication_provider_name.rb
lib/puppet/type/wls_identity_asserter/defaultmappertype.rb
lib/puppet/type/wls_identity_asserter/order.rb
lib/puppet/type/wls_identity_asserter/providerclassname.rb
manifests/utils/fmwcluster.pp

Hey Edwin, here's some enhancements.
* wls_datasource include xaproperties
* identity asserter type added for customising defaultidentityasserter
* better error handling for auth provider ordering
* optional retain file based security store in fmwcluster.pp
* readme updates to explain all the above
Cheers,
Brad

Type enhancements + option for file based security store

---

files/providers/wls_datasource/create.py.erb
files/providers/wls_datasource/index.py.erb
files/providers/wls_datasource/modify.py.erb
lib/puppet/type/wls_datasource.rb
lib/puppet/type/wls_datasource/connectioncreationretryfrequency.rb
lib/puppet/type/wls_datasource/secondstotrustidlepoolconnection.rb
lib/puppet/type/wls_datasource/testfrequency.rb

* secondstotrustidlepoolconnection
* testfrequency
* connectioncreationretryfrequency

Extra properties added to wls_datasource

---

README.markdown
files/providers/wls_singleton_service/create.py.erb
files/providers/wls_singleton_service/destroy.py.erb
files/providers/wls_singleton_service/index.py.erb
files/providers/wls_singleton_service/modify.py.erb
lib/puppet/provider/wls_singleton_service/simple.rb
lib/puppet/type/wls_singleton_service.rb
lib/puppet/type/wls_singleton_service/additional_migration_attempts.rb
lib/puppet/type/wls_singleton_service/class_name.rb
lib/puppet/type/wls_singleton_service/cluster.rb
lib/puppet/type/wls_singleton_service/constrained_candidate_servers.rb
lib/puppet/type/wls_singleton_service/millis_to_sleep_between_attempts.rb
lib/puppet/type/wls_singleton_service/notes.rb
lib/puppet/type/wls_singleton_service/singleton_service_name.rb
lib/puppet/type/wls_singleton_service/user_preferred_server.rb

Again: if you see any problems, let me know!

Implement wls_singleton_service resource

---

manifests/fmw.pp

Running SuSE with restricted access to /tmp,

Minor issue in temp file location

---

README.markdown
files/providers/wls_coherence_server/create.py.erb
files/providers/wls_coherence_server/modify.py.erb
lib/puppet/type/wls_coherence_server/unicastport.rb

* Coherence machine was hardcoded to localmachine by mistake.
* Add some basic documentation.

Fix coherence machine and add readme.

---

lib/puppet/type/wls_group/users.rb

This fixes the error:
Error: undefined method `sort' for :absent:Symbol

Fix empty user group.

---

files/providers/wls_deployment/modify.py.erb

Python script contained indenting errors.

Fixed deployment update

---

README.markdown
files/providers/wls_datasource/index.py.erb

Hi Edwin,
This is a fix to make xaproperties in the wls_datasource type idempotent. It's not the best fix in the world, I think it would be better to maybe provide them as seperate parameters. I hope to be able to pick that up in the future.
For the moment, this seems to work in my implementation. I did all the testing I could do and it seems to be working fine.
Please merge if you agree on the solution.
Thanks!
Kr,
Bas

Xaproperties fix

---

files/providers/wls_server/create.py.erb
files/providers/wls_server/index.py.erb
files/providers/wls_server/modify.py.erb
lib/puppet/type/shared/frontendhost.rb
lib/puppet/type/shared/frontendhttpport.rb
lib/puppet/type/shared/frontendhttpsport.rb
lib/puppet/type/wls_server.rb

Ability to set FRONTENDHOST, HTTPPORT & HTTPSPORT within wls_server - taken from wls_cluster type. I'm not convinced that's idempotent though, so I've changed to allow removal of frontendhost. With the wls_cluster implmentation it looked like you could set a host but never remove it.
Change-Id: I30ea09de5f8deb17d1609c16c4e680e47e4deafe

Added frontendhost httpport & httpsport to wls_server. Slightly changed

---

README.markdown

This should save someone from trouble.

xaproperties in hiera example was wrong

---

manifests/resourceadapter.pp
templates/adapter_plans/Plan_File.xml.erb

Some BAM fixes and FileAdapter

---

files/providers/wls_jms_queue/create.py.erb
files/providers/wls_jms_queue/index.py.erb
files/providers/wls_jms_queue/modify.py.erb
lib/puppet/type/wls_jms_queue.rb
lib/puppet/type/wls_jms_queue/deliverymode.rb

Hey Edwin, This change adds the 'deliverymode' attribute to the 'wls_jms_queue' type.

Added deliverymode attribute to wls_jms_queue type

---

files/providers/wls_jms_topic/create.py.erb
files/providers/wls_jms_topic/index.py.erb
files/providers/wls_jms_topic/modify.py.erb
lib/puppet/type/wls_jms_topic.rb
lib/puppet/type/wls_jms_topic/deliverymode.rb

Hey Edwin,
This is a pull request to add the `deliverymode` attribute to the `wls_jms_topic` type. It's pretty much the same thing as the pull request I recently submitted for the `wls_jms_queue` type.
Thanks!
Bryan

Added deliverymode attribute to wls_jms_topic type

---

files/providers/wls_migratable_target/create.py.erb
files/providers/wls_migratable_target/destroy.py.erb
files/providers/wls_migratable_target/index.py.erb
files/providers/wls_migratable_target/modify.py.erb
lib/puppet/provider/wls_migratable_target/simple.rb
lib/puppet/type/wls_migratable_target.rb
lib/puppet/type/wls_migratable_target/cluster.rb
lib/puppet/type/wls_migratable_target/constrained_candidate_servers.rb
lib/puppet/type/wls_migratable_target/migratable_target_name.rb
lib/puppet/type/wls_migratable_target/migration_policy.rb
lib/puppet/type/wls_migratable_target/number_of_restart_attempts.rb
lib/puppet/type/wls_migratable_target/seconds_between_restarts.rb
lib/puppet/type/wls_migratable_target/user_preferred_server.rb

Adding support migratable targets provider types

Migratabletargets

---

files/providers/wls_authentication_provider/index.py.erb
files/providers/wls_cluster/index.py.erb
files/providers/wls_coherence_server/index.py.erb
files/providers/wls_datasource/index.py.erb
files/providers/wls_domain/index.py.erb
files/providers/wls_dynamic_cluster/index.py.erb
files/providers/wls_foreign_server/index.py.erb
files/providers/wls_identity_asserter/index.py.erb
files/providers/wls_jdbc_persistence_store/index.py.erb
files/providers/wls_jms_bridge_destination/index.py.erb
files/providers/wls_jms_connection_factory/index.py.erb
files/providers/wls_jms_queue/index.py.erb
files/providers/wls_jms_template/index.py.erb
files/providers/wls_jms_topic/index.py.erb
files/providers/wls_jmsserver/index.py.erb
files/providers/wls_mail_session/index.py.erb
files/providers/wls_messaging_bridge/index.py.erb
files/providers/wls_migratable_target/index.py.erb
files/providers/wls_multi_datasource/index.py.erb
files/providers/wls_singleton_service/index.py.erb

This PR allow the code to diffrentiate between an empty string and a null value. I've taken the liberty to fix this in *all* index scripts. This means it is potentialy a dangerous fix.
I've tested in on a prettu big configuration, but I think we need some more tests.

Fix difference between empty string and null values

---

files/providers/wls_server_tlog/create.py.erb
files/providers/wls_server_tlog/destroy.py.erb
files/providers/wls_server_tlog/index.py.erb
files/providers/wls_server_tlog/modify.py.erb
lib/puppet/provider/wls_server_tlog/simple.rb
lib/puppet/type/wls_server_tlog.rb
lib/puppet/type/wls_server_tlog/server_name.rb
lib/puppet/type/wls_server_tlog/tlog_datasource.rb
lib/puppet/type/wls_server_tlog/tlog_datasource_prefix.rb
lib/puppet/type/wls_server_tlog/tlog_enabled.rb

This is a new provider to allow Tlog configuration on the managed servers. Tied to issue #225

Tlogconfiguration

---

manifests/domain.pp
templates/domains/extensions/osb_template.py.erb

I need to do a bit more testing, but this is what I'm proposing so far...

RFC: Optionally install OWSM when creating a weblogic 10.3.6 OSB domain

---

files/providers/wls_jms_topic/create.py.erb
files/providers/wls_jms_topic/index.py.erb
files/providers/wls_jms_topic/modify.py.erb
lib/puppet/type/wls_jms_topic.rb
lib/puppet/type/wls_jms_topic/forwardingpolicy.rb

This commit adds the ability to set the forwarding policy for a
distributed topic.
It also fixes a bug, which causes the logic to never enter the
conditional statement set for the distributed variable in de modify and
create operations.

Add Forwarding Policy for distributed topics

---

manifests/copydomain.pp
manifests/packdomain.pp

added JAVA_HOME to exec in packdomain.pp without it it breaks in my SLES setup

added JAVA_HOME to exec in packdomain.pp.

---

lib/puppet/type/wls_jms_bridge_destination/connectionfactoryjndi.rb

This causes a problem when trying to read the code in Geppetto

Remove the quoted '

---

manifests/fmw.pp

With these changes, I was able to deploy SOA Suite 12.2.1 Quick Start Installer.
I have not tested 12.1.3 or earlier.

Add soa quickstart install.

---

files/wlst/common.py.erb

Edwin,
Can you try this? This should fix your problems at WebLogic 10.3

Fix functions to also run on WebLogic 10.3

---

templates/domains/extensions/osb_template.py.erb

was getting a NameError here previously

bug fix for standalone OSB domain

---

files/providers/wls_foreign_server/destroy.py.erb
files/providers/wls_saf_imported_destination/destroy.py.erb

If you wanted to remove a foreign servers, it shown an error.

Fix syntax, changed +name')) to +name))

---

templates/domains/extensions/jrf_template.py.erb

I noticed this changed in most of the other templates.

Fix NameError problem with changeDatasource

---

templates/wlst/wlstexec/fmw/assignOsbSoaBpmBamToClusters_1213.py.erb

Un-targeted the below deployments from the Admin server:
Service Bus Email Transport Provider
Service Bus File Transport Provider
Service Bus FTP Transport Provider
Service Bus SFTP Transport Provider

Fix for 'OSB 12c deployments in warning state #335' - OSB1213

---

lib/utils/wls_daemon.rb

See https://github.com/biemond/biemond-orawls-vagrant-12.2.1/issues/4
for more information

t3s is not working without -Dweblogic.security.SSL.enableJSSE=true

---

manifests/copydomain.pp

See https://github.com/biemond/biemond-orawls/issues/350
Solves the problem Notice:
/Stage[main]/Profiles::Wls::Copy_domain/Orawls::Copydomain[soa_domain]/E
xec[execwlst soa_domain soa_domain]/returns:
javax.net.ssl.SSLException: Received fatal alert: unexpected_message;
No available router to destination]

add extra java parameter to copydomain

---

manifests/nodemanager.pp

From now on, whenever the properties file of a NodeManager changes, the
corresponding NodeManager is restarted automatically.

Added refresh behavior to the NodeManager.

---

lib/puppet/provider/bsu_patch/bsu_patch.rb
lib/puppet/provider/opatch/opatch.rb
lib/puppet/provider/wls_domain_partition_control/wls_domain_partition_control.rb
lib/puppet/provider/wls_managedserver/wls_managedserver.rb

Sorry i missed few more files before all thanks to my wrong search patterns i searched in all files for these changes.
Eventually i found additional files that needed modifications to run as non-root.
Can you please check these as well?

non-root support - additional files

---

README.markdown
manifests/control.pp
manifests/copydomain.pp
manifests/domain.pp
manifests/fmw.pp
manifests/nodemanager.pp
manifests/weblogic.pp
manifests/weblogic_type.pp
templates/domains/domain.py.erb
templates/domains/extensions/bam_template.py.erb
templates/domains/extensions/osb_template.py.erb
templates/domains/extensions/soa_osb_template.py.erb
templates/domains/extensions/soa_template.py.erb

And minor typo in control.pp; extra , after '#' comment in parameters

Updated to version 12.2.1.2

---

manifests/fmw.pp
manifests/utils/orainst.pp

Hi, Edwin.
PR as we spoke at issue #406 .

Ora inst mode

---

README.markdown
manifests/fmw.pp
templates/fmw_silent_wcs_1221.rsp.erb

WebCenter sites can now be installed just like other FMW installations.
#409

Added FMW Product WebCenter Sites 

---

manifests/domain.pp
manifests/utils/rcu.pp
templates/domains/domain_1221.py.epp
templates/domains/extensions/wcs_template.py.erb

Only WCS will use the new domain_1221.py.epp for now. Added an extension as suggested.

Added support for webcenter sites 12.2.1.2

---

manifests/copydomain.pp
manifests/resourceadapter.pp
manifests/utils/webtier.pp

I have missed the $ in the password issue in couple of other places. Please accept my pull request.

Fixing the $ in the password issue in other places

---

files/providers/wls_jms_connection_factory/create_modify.py.erb
files/providers/wls_jms_connection_factory/index.py.erb
lib/puppet/type/wls_jms_connection_factory.rb
lib/puppet/type/wls_jms_connection_factory/clientid.rb

Give the option of setting a client id on the JMS connection factory

configure a Client ID on the JMS connection factory

---

manifests/domain.pp
manifests/utils/rcu.pp
templates/domains/extensions/forms_template.py.erb

Vagrant env: https://github.com/bFekete/biemond-orawls-vagrant-12.2.1-infra-forms-puppet4

Added forms 12c domain creation

---

files/providers/wls_jmsserver/create_modify.py.erb
files/providers/wls_jmsserver/index.py.erb
lib/puppet/type/wls_jmsserver.rb
lib/puppet/type/wls_jmsserver/messages_maximum.rb

Hello @biemond ,
I implemented the property "messages_maximum" in the jmsserver.
As I asked in the issue #489.
Can you approve it? Please.
Thank you.

[wls_jmsserver] Add propeties messages-maximum

---

manifests/utils/forms11gpatch.pp

Please see the commit below to fix an exec resource in the forms11gpatch class

Fixed forms11gpatch exec to only run once
