files/providers/wls_datasource/create.py.erb
files/providers/wls_datasource/index.py.erb
files/providers/wls_datasource/modify.py.erb
lib/puppet/type/wls_datasource.rb
lib/puppet/type/wls_datasource/mincapacity.rb
lib/puppet/type/wls_datasource/statementcachesize.rb
lib/puppet/type/wls_datasource/testconnectionsonreserve.rb

ConnectionPool properties such as mincapacity, statement cache size &
test connection on reserve can be now set via puppet by setting below:
mincapacity =
statementcachesize =
testconnectionsonreserve = '0 or 1'
If not passed will be defaults.

More properties setting enabled for datasources tuning in wls_datasource

---

lib/puppet/type/wls_datasource/globaltransactionsprotocol.rb

LoggingLastResource was missing from the available options on the globaltransactionsprotocol attribute of a datasource.

Added LLR to datasource global transactions protocol

---

files/providers/wls_foreign_server_object/destroy.py.erb

`ensure => 'absent'` on foreign destinations and foreign connection factories didn't work prior to this.
As my project seems to need this, I took it upon myself to implement it. If there are any issues, let me know!

Implement destroying of foreign destinations/connection factories.

---

manifests/domain.pp
manifests/nodemanager.pp

Hi Edwin,
I noticed an issue with starting nodemanager after creating a WLS 1213 domain. If log_dir is not specified, the logfile entry in the nodemanager.properties is empty. Nodemanager will then not start. 
It took me some time to figure out what was wrong due to the very descriptive error message from nodemanager, but I have fixed this.
Please consider merging this to your branch. 
Kind regards,
Bas
P.S. I also removed a duplicate entry in nodemanager.pp

Solved issue with empty log_dir in domain creation

---

files/providers/wls_jms_bridge_destination/create.py.erb
files/providers/wls_jms_bridge_destination/modify.py.erb

For wls_jms_bridge_destination: when below is passed:
name                        = 'Destination-Source'
adapter                     = 'eis.jms.WLSConnectionFactoryJNDIXA'
classpath                   = ''
connectionfactoryjndi       = 'weblogic.jms.XAConnectionFactory'
connectionurl               = ''
destinationjndi             = 'JMS.SourceQueue'
destinationtype             = 'Queue'
initialcontextfactory       = 'weblogic.jndi.WLInitialContextFactory'
user_name                   = ''
password                    = ''
Its sets password field in WLS with some unknown value it seems.
As per WLS help:
When you set the value of this attribute, WebLogic Server does the
following:
1. Encrypts the value.
2. Sets the value of the UserPasswordEncrypted attribute to the
encrypted value.
As the …

wls_jms_bridge_destination - Password set when no value is passed

---

files/providers/wls_jms_module/create.py.erb
files/providers/wls_jms_module/modify.py.erb

For wls_jms_module, the set target does not supports more than 1 target,
thus failing if more than 1 targets are passed to it.
Modified create.py & modify.py to support multiple targetting for an JMS
Module

Multiple targets for wls_jms_module

---

files/providers/wls_deployment/create.py.erb
files/providers/wls_deployment/index.py.erb
files/providers/wls_deployment/modify.py.erb
lib/puppet/type/wls_deployment.rb
lib/puppet/type/wls_deployment/remote.rb
lib/puppet/type/wls_deployment/stagingmode.rb
lib/puppet/type/wls_deployment/upload.rb

Added property "stagingmode" to set stageMode in wls_deployment for
multi-node cluster.
Added more property for remote & upload options in deploy(). This was
done to set this option for different stageMode such as "nostage"
Parameters added:
stagingmode ->Valid values are stage, nostage, and external_stage
remote -> 0 or 1 (Defaults 1 (true))
upload -> 0 or 1 (Defaults 1 (true))
Ex.
deployment_application_instances:
'webapp':
ensure:            'present'
deploymenttype:    'AppDeployment'
versionidentifier: '1.1@1.1.0.0'
stagingmode:    "nostage"
remote:         "1"
upload:         "0"
target:
- 'AdminServer'
- 'WebCluster'
targettype:
- 'Server'
- 'Cluster'
localpath:         '/vagrant/webapp.war'

Setting stageMode support for wls_deployment for multi-node cluster

---

lib/facter/orawls.rb
manifests/resourceadapter.pp
templates/adapter_plans/Plan_FTP.xml.erb
templates/adapter_plans/createResourceAdapterEntry.py.erb

Added FTP adapter
Now it is possible to add more key/values in Adapter config, example:
adapter_entry_property:
'FtpAbsolutePathBegin;FtpPathSeparator;Host;ListParserKey;Password;ServerType;UseFtps;Username;UseSftp'
adapter_entry_value:
'/BDDC;/;l2-ibrfongen02.nl.rsg;UNIX;;unix;false;kim;false'

Add FTP Resource Adapter, multiple adapter_entry_property possible

---

lib/puppet/type/wls_jms_queue/forwarddelay.rb

I've removed the default attribute from the custom type. This way the original code works, unless the forwarddelay attribute is set. The other way would be to change the generated WLST code to check the distributed flag. But I suspect the default WLS setting is -1 for a distributed queue anyway.

Removed default forwarddelay attribute value

---

files/providers/wls_datasource/index.py.erb

When the attributes SecondsToTrustAnIdlePoolConnection and Connection…CreationRetryFrequencySeconds contain the value '0' then nill is used instead of '0'

BugFix: secondstotrustidlepoolconnection of type Wls_datasource is not idempotent

---

files/providers/wls_jdbc_persistence_store/create.py.erb
files/providers/wls_jdbc_persistence_store/destroy.py.erb
files/providers/wls_jdbc_persistence_store/index.py.erb
files/providers/wls_jdbc_persistence_store/modify.py.erb
lib/puppet/provider/wls_jdbc_persistence_store/simple.rb
lib/puppet/type/wls_jdbc_persistence_store.rb
lib/puppet/type/wls_jdbc_persistence_store/datasource.rb
lib/puppet/type/wls_jdbc_persistence_store/jdbc_persistence_name.rb
lib/puppet/type/wls_jdbc_persistence_store/prefix_name.rb

Hi Edwin,
I've added a custom type/provider for managing JDBC persistence stores. I've tested create/modify/delete on a Weblogic 10.3.6 instance on CentOS 6.4.
Bryan

Add support for managing JDBC persistence stores in Weblogic domain

---

files/providers/wls_jms_queue/index.py.erb

When the attribute ForwardDelay contains the value '0' then nill is used instead of '0'

BugFix: forwarddelay of type wls_jms_queue is not idempotent

---

files/providers/wls_deployment/modify.py.erb

This resoles the following error message When VersionIdentifier is null:
TypeError: cannot concatenate 'str' and 'NoneType' objects

Fix wls_deployment updates when version is none.

---

manifests/bsu.pp
templates/weblogic_silent_install.xml.erb

The path for WebLogic's home was hard coded in bsu.pp to where Oracle installs it by default. Also had to add the `WLS_INSTALL_DIR` setting in the silent install file so that WebLogic would know to install in a non-default location. I did this per http://docs.oracle.com/cd/E23943_01/doc.1111/e14142/silent.htm#WLSIG134

Fixes issue where weblogic_home_dir is ignored during WebLogic install

---

README.markdown
files/providers/wls_domain/index.py.erb
files/providers/wls_domain/modify.py.erb
lib/puppet/type/wls_domain.rb
lib/puppet/type/wls_domain/setarchiveconfigurationcount.rb
lib/puppet/type/wls_domain/setconfigbackupenabled.rb
lib/puppet/type/wls_domain/setconfigurationaudittype.rb
lib/puppet/type/wls_domain/setinternalappdeploymentondemandenable.rb

This adds the following options to the domain type:
1. Configuration backup / archiving flag switching
2. specifying how many backups you want to keep of the configuration archive
3. Flag switching for the internal application deployment option
4. Configuration audit manipulation.

Add domain options

---

files/providers/wls_jms_connection_factory/create.py.erb
files/providers/wls_jms_connection_factory/modify.py.erb

It used to set the `serveraffinity` based on the property `loadbalancingenabled`. This commit fixes this.

Fix setting loadbalancing enable

---

lib/puppet/type/shared/target.rb

This was a problem when managing datasources that had become
untargetted.
Fixes https://github.com/biemond/biemond-orawls/issues/212
Fix as suggested by Bert Hajee https://github.com/hajee

Fix "undefined method `sort' for :absent:Symbol"

---

files/providers/wls_foreign_server/create.py.erb
files/providers/wls_foreign_server/modify.py.erb
files/providers/wls_jms_connection_factory/create.py.erb
files/providers/wls_jms_connection_factory/modify.py.erb
files/providers/wls_jms_queue/create.py.erb
files/providers/wls_jms_queue/modify.py.erb
files/providers/wls_jms_topic/create.py.erb
files/providers/wls_jms_topic/modify.py.erb
files/providers/wls_saf_imported_destination/create.py.erb
files/providers/wls_saf_imported_destination/modify.py.erb

Hi Edwin,
I noticed that the wls_jms_topic and wls_jms_queue types did not interpreted the defaulttargetting parameters for the both. I also made a small change to wls_jms_connection_factory.
The logic goes in favorite of defaulttargetting if both defaulttargetting and subdeployment are set, because the first is the exception in our environment on the latter. I don't know if this is a common use case, so this might need some refactoring. I don't know what your experiences are on this topic.
Cheers!
Bas

Change defaulttargetting behavior for jms components

---

lib/puppet/provider/opatch/opatch.rb
lib/puppet/type/opatch.rb
manifests/opatch.pp

OPatch definition is now differentiated on title, allowing same patch ID
to be applied to different homes.
This resolves Issue #221

Allow Same OPatch to Multiple Homes

---

Rakefile
lib/puppet/type/wls_deployment/localpath.rb
spec/spec_helper.rb
spec/unit/puppet/type/wls_deployment_spec.rb

Fixes #239
With weblogic 12.1.1, wls_deployments would silently fail if the
deployment's localpath was in /tmp.
This patch validates that localpath is both an absolute path and not
directly under /tmp.

Validate wls_deployment 'localpath' parameter

---

.gitignore
manifests/fmw.pp
spec/defines/fmw_remote_spec.rb
spec/defines/fmw_spec.rb

The current version of fmw, doesn't support the installation of the same middleware more than once. If you try, you get duplicate resources.  If however you want to have a middleware home for SOA and one for BAM and apply different patches to these, you'll need to do just that. This PR add's support for installing multiple homes with the same version. You will have to use different titles to the fmw to do this.  After this you can use opatch to differentiate the middleware homes

Add support for multiple base installations of same Fmw

---

lib/puppet/provider/opatch/opatch.rb

Due to strange issues with Opatch not detecting patches applied to the
local system, this change has been made after it being tested
succesfully.
Fixes #245

Add cast to patch id comparison

---

lib/puppet/provider/wls_opatch/prefetching.rb
lib/puppet/type/wls_opatch.rb
lib/puppet/type/wls_opatch/jdk_home_dir.rb
lib/puppet/type/wls_opatch/oracle_product_home_dir.rb
lib/puppet/type/wls_opatch/orainst_dir.rb
lib/puppet/type/wls_opatch/os_user.rb
lib/puppet/type/wls_opatch/patch_id.rb
lib/puppet/type/wls_opatch/source.rb

Create's a `wls_opatch`  type. This type is a little bit smarter than the existing `opatch`. 
- It only does an index operation once. This means dramatic speed improvements when applying a lot of patches.
- it can unzip the provided file. It will only do this if it decides the patch must be installed.  This means no more exec's doing needless unzips.
Although not implemented yet, it is prepared for using `puppet:\\....` source files. This means it can fetch the file from a Puppet file server, but will only do this if it has decided the patch needs to be installed. Again this will take care of the needless fetching of large patch files.
You can use the type like this:
```puppet
wls_opatch{'/middleware_home_dir:patch_number':
ensure   => present
os_user  => 'weblogic'
os_group => 'oinstal', …
```

Prefetching wls_opatch type

---

.fixtures.yml
manifests/nodemanager.pp
metadata.json
templates/nodemgr/nodemanager.properties.erb
templates/nodemgr/nodemanager.properties_1212.erb
templates/nodemgr/nodemanager.properties_1213.erb

I added a `properties` parameters to the nodemanager defined type. This takes a hash of nodemanager properties that get applied to nodemanager.properties file (via the erb templates). All properties have defaults that get overridden by the properties parameter.
I needed to add puppetlabs' stdlib module to allow the hash merge. I hope that's ok.

Add ability to manage nodemanager properties file.

---

lib/puppet/type/wls_setting.rb
lib/puppet/type/wls_setting/archive_path.rb
lib/puppet/type/wls_setting/debug_module.rb
lib/utils/wls_access.rb

This commit adds the use of a temp directory to orawls. When you create
the following line in wls_settings on the host the module is ran,
orawls will copy all the scripts created as tempfiles to
/tmp/orawls-archive. This is useful when new or modified types are debugged.
debug_module: "true"
wls_settings needs to be changed, so we can puppetize this value as
well.

Add debug capabilities to orawls

---

files/providers/wls_exec/execute.py.erb
lib/puppet/provider/wls_exec/simple.rb
lib/puppet/provider/wls_exec/wlst.rb
lib/puppet/type/wls_exec.rb
lib/puppet/type/wls_exec/cwd.rb
lib/puppet/type/wls_exec/logoutput.rb
lib/puppet/type/wls_exec/refreshonly.rb
lib/puppet/type/wls_exec/statement.rb
lib/puppet/type/wls_exec/unless.rb

This PR allows you easy access to wls from Puppet. Just like `exec` and `ora_exec`, it allows you to execute statements or scripts. This is useful when you need to do very specific stuff that is not (yet) supported by the custom types.
```puppet
wls_exec{"domain\print 'hallo'":}
```
execute the `print "hallo"`  statement in the logged in wlst context. Obvious, this doesn't really help. But you can also use other more helpfull statements.
You can also execute scripts.
```puppet
wls_exec{"domain\@tmp/create_wls_resource.wlst":}
```
This will execute the content of the specified script.
You can also execute a check before executing the real content. This is the way to make idempotent Puppet statements
```puppet
wls_exec{"domain\@tmp/create_wls_resource.wlst":
unless => …
```

wls_exec implementation

---

files/providers/wls_server/create.py.erb
files/providers/wls_server/modify.py.erb
lib/puppet/type/wls_server/arguments.rb

The original code just took arguments as a simple string.  The code was then improved to
accept arrays too.  Arrays were flattened to newline separated strings before being passed
to the template.
A few issues with this.
Weblogic actually preferred server arguments as space separated strings.
In weblogic 12.1, if you use the web interface to enter arguments one per line, they get
converted to space separated when you hit 'save'.
If an array was used to set arguments, output from puppet resource was as the newline separated
string.  This looked a bit nasty.  It would have been much nicer to have puppet return an array
of arguments no matter how they were created.
The order of the arguments would be taken into account when comparing is and should
values.  Things that should probably have …

Improve wls_server 'arguments' property

---

lib/puppet/type/wls_exec/statement.rb
lib/utils/wls_access.rb

This PR fixes an issue when using `wls_exec` on a multidomain setup. It would run the unless statement on all domains. This PR fixes this. I have refactered the wls_access code a little bit to allow this

Running the wls_exec unless statement only on specfied domain

---

templates/adapter_plans/createResourceAdapterEntry.py.erb

For example:
```pupet
orawls::resourceadapter { 'JmsAdapter_AMV':
adapter_name           => 'JmsAdapter',
adapter_path           => "/opt/oracle/soat/middleware/soa/soa/connectors/JmsAdapter.rar",
adapter_plan_dir       => "${plan_dir}",
adapter_plan           => 'JmsAdapter.xml',
adapter_entry          => 'eis/MQChannel/AMV',
adapter_entry_property => 'ConnectionFactoryLocation;FactoryProperties;IsTransacted;Username',
adapter_entry_value    => 'com.ibm.mq.jms.MQXAQueueConnectionFactory;QueueManager=QUEMGR1\;TransportType=1\;HostName=10.10.10.10\;Port=1414\;Channel=AXA.QMGR\;ThirdPartyJMSProvider=true;true;mqm',
}
```

Allow escaping the semicolon in the properties of a resource adapter.

---

files/providers/wls_server/create.py.erb

Check arguments isn't nil before calling 'join' on it.
Fixes following error when creating wls_server...
```
puppet apply -e 'wls_server{"default/test": ensure => present, machine => "LocalMachine"}'
'Error: /Stage[main]/Main/Wls_server[default/test]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method `join' for nil:NilClass in 1'
```

Fix creating wls_server with no arguments

---

manifests/nodemanager.pp

If using parameter log_dir and the directory doesn't exist nodemanager fails to start. The log_dir is  created but it needs to be before the exec to start nodemanager. I also think that the exec may need to change so any error is captured, but at the minute it fails silently. A second puppet run resolves the issue because the directories are created on the first run. Adding a before to the log_dir creation resolves the issue.

Nodemanager fails to start first time if param log_dir is used and directory doesn't exist

---

files/providers/wls_datasource/create.py.erb
files/providers/wls_datasource/index.py.erb
files/providers/wls_datasource/modify.py.erb
lib/puppet/type/shared/wrapdatatypes.rb
lib/puppet/type/wls_datasource.rb

Add property to manage connection pool advanced switch 'Wrap Data Types'.
Defaults to 'on' if not specified same as weblogic.
There are no spec tests for this property.
I have tested deployments with wrapdatatypes set on, off and not specified.

Add wrapdatatypes property

---

lib/puppet/provider/wls_rcu/wls_rcu.rb

was getting this error originally when this breaks down (in my case a java_home issue).  To duplicate point wlst.sh to an invalid Java_Home and try rcu create.  Errors are descriptive after this change, unlike the below:
Orawls::Domain[wlsdomain cl8625]/Orawls::Utils::Rcu[RCU_12c wlsdomain cl8625]/Wls_rcu[SOA12POC]) Could not evaluate: undefined local variable or method `output' for #<Puppet::Type::Wls_rcu::ProviderWls_rcu:0x7fe23a4c3f28>

fix wls_rcu error handling

---

lib/orawls_core.rb

This commit fixes the load of easy_type in specific situations. Due to
the ways the Puppet masters are setup at our environment, the catalogue
failed to compile as it was unable to find easy_type. Even though it was
present and working fine in a local Vagrant box, we were puzzled why
this did not work.
Eventually, we involved someone from the Puppetlabs module team, who
proposed this fix. I discussed if this could be committed back upstream
/ was backwards compatible and he confirmed.
Long story short, this commit fixes the way easy_type is put in the
Ruby load path and fixes a long outstanding production issue in our
environment.

Fix easy_type load issues in specific situation

---

files/providers/wls_authentication_provider/create.py.erb
files/providers/wls_authentication_provider/fetch.py.erb
files/providers/wls_authentication_provider/modify.py.erb
lib/puppet/provider/wls_authentication_provider/prefetching.rb
lib/puppet/provider/wls_authentication_provider/simple.rb
lib/puppet/type/wls_authentication_provider.rb
lib/puppet/type/wls_authentication_provider/attributes.rb
lib/puppet/type/wls_authentication_provider/attributesvalues.rb
lib/puppet/type/wls_authentication_provider/provider_specific.rb

This PR provides the `provider_specific`  propery on `wls_authentication_provider`. Using this property, you can manage the attributes from any type of authentication_provider. This PR also add's deprecation messages to `attributes` and `attributesvalues`.

Add support for provider_specific attributes on wls_authentication_provider

---

manifests/utils/fmwcluster.pp

Without Hiera, fmwcluster resource won't work since there is no way to pass in a middleware_home_dir to orawls::control

fmwcluster support without Hiera

---

lib/puppet/type/wls_cluster.rb

When creating a cluster the server channel must exists otherwise the creation of the cluster will fail.

Added autorequire for wls_server_channel.

---

files/providers/wls_datasource/create.py.erb
files/providers/wls_datasource/index.py.erb
files/providers/wls_datasource/modify.py.erb
lib/puppet/type/wls_datasource.rb
lib/puppet/type/wls_datasource/removeinfectedconnections.rb
spec/unit/puppet/type/wls_datasource_spec.rb

For consistency accepts '0', '1' as well as true/false.  Property is optional.  If not specified in a manifest, the existing state will not be altered.  See commits for more detailed comments.

Add new 'removeinfectedconnections' property to wls_datasource

---

README.markdown
files/providers/wls_jms_security_policy/create.py.erb
files/providers/wls_jms_security_policy/destroy.py.erb
files/providers/wls_jms_security_policy/index.py.erb
files/providers/wls_jms_security_policy/modify.py.erb
lib/puppet/provider/wls_jms_security_policy/simple.rb
lib/puppet/type/wls_jms_security_policy.rb
lib/puppet/type/wls_jms_security_policy/action.rb
lib/puppet/type/wls_jms_security_policy/authorizationprovider.rb
lib/puppet/type/wls_jms_security_policy/destinationtype.rb
lib/puppet/type/wls_jms_security_policy/policyexpression.rb
lib/puppet/type/wls_jms_security_policy/resourcename.rb

Hey Edwin,
This is a new custom type/provider for managing the security policies on JMS queues and topics. It handles adding a policy, removing a policy and updating a policy. It uses the policy expression syntax. The easiest way to figure out the right string for a policy expression is to create it manually in admin console then use WLST to call `getPolicyExpression()`.
It has been tested on CentOS 6.6 and Weblogic 10.3.6.
Let me know if there's anything you'd like me to change.
Bryan

Add type and provider for managing JMS resource security policies.

---

lib/puppet/provider/wls_adminserver/wls_adminserver.rb
lib/puppet/type/wls_adminserver.rb
manifests/control.pp
manifests/domain.pp
manifests/fmw.pp
manifests/nodemanager.pp
templates/ohs/domain.py.erb
templates/web_http_server_1212.rsp.erb

The changes made in this PR allows the module to install and configure OHS server in standalone mode. Also made a workaround to avoid dependency problems with defined "File" resources which are responsible to create some directories needed for Weblogic and/or OHS installation. Fix #319

OHS Standalone installation

---

files/wlst/common.py.erb

Bugfix for cases when setting an attribute's value to 0 would cause the attribute to not be set at all (even though Puppet would report it as being changed).

Bugfix for cases when setting an attribute's value to 0

---

manifests/weblogic_type.pp

If weblogic is defined as class it is possible to install single instance of WLS on host. 
It is quite easy to redefine weblogic as type. In this case it is possible to install multiple instances of WLS on single host/filesystem which is requirement in our situation.

Define weblogic as type to be able to install multiple instances of WLS

---

files/wlst/common.py.erb

Previously, while using this module, I wasn't able to use some of the module's defined types (particularly wls_server) due to no support for JRockit. After much effort, I've discovered that in order to use JRockit and this module, a python library must be imported in order for it to work. Thus, inclusion of this code (one line) will result in everyone else being able to use this module along with JRockit if they so desire to.

Support for JRockit

---

lib/utils/wls_access.rb

Not actually tested this commit yet, but I was hitting this error.
```
Error: Failed to apply catalog: undefined local variable or method `weblogicConnectUrL' for Puppet::Type::Wls_domain:Class
```

Fix weblogicConnectUrL typo

---

lib/puppet/provider/opatch/opatch.rb
lib/puppet/provider/wls_opatch/prefetching.rb
lib/utils/wls_access.rb

More Puppet.info changes to Puppet.debug.
I've modified the opatch class to never log to info anymore, this might be improved to an if statement that it only logs when it's executing an actual OPatch installer.
The current code logs an lsinventory command on every run, which clutters the log.

Modified Puppet.info -> Puppet.debug for puppet run log cleanup

---

lib/puppet/provider/wls_adminserver/wls_adminserver.rb
lib/puppet/type/wls_adminserver.rb
manifests/control.pp
manifests/nodemanager.pp

See https://github.com/biemond/biemond-orawls/issues/356
Also adding the extra parameter to start wls admin.
Info: adminserver action: start with command
/opt/wls/middleware11g/wlserver_10.3/common/bin/wlst.sh
-skipWLSModuleScanning <<-EOF
nmConnect("weblogic","xxxxx","192.168.234.95",5556,"soa_domain","/opt/wl
s/wlsdomains/domains/soa_domain","ssl")
nmStart("AdminServer")
nmDisconnect()
EOF and CONFIG_JVM_ARGS=-Dweblogic.ssl.JSSEEnabled=true
-Dweblogic.security.SSL.enableJSSE=true
-Dweblogic.security.TrustKeyStore=CustomTrust
-Dweblogic.security.CustomTrustKeyStoreFileName=/opt/ssl/keystore/trusts
tore.jks -Dweblogic.security.CustomTrustKeystorePassPhrase=welcome
-Dweblogic.security.SSL.minimumProtocolVersion=TLSv1
Info: adminserver result:

Add extra java parameter to node manager

---

lib/facter/orawls.rb
lib/puppet/provider/wls_rcu/wls_rcu.rb
lib/puppet/type/wls_opatch.rb
manifests/copydomain.pp
manifests/domain.pp
manifests/fmw.pp
manifests/nodemanager.pp
manifests/opatch.pp
manifests/utils/orainst.pp
manifests/weblogic_type.pp

*alternative /etc/oraInst.loc location can be set through by adding facter “override_oraInstPath” and hiera value oraInstPath_location. ora_wls manifests updated to use new location if defined.
*rcu updated so it doesn’t try to switch to root then to os_ouser when running as non root
*opatch unzip updated so it doesn’t try to switch to root then to os_ouser when running as non root
This should now fully certify orawls to run as non root

Various updates for non-root support

---

lib/puppet/provider/wls_managedserver/wls_managedserver.rb

Puppet was hanging when trying to refresh my soa_server1
`wls_managedserver`.
After ctrl-c'ing puppet and stopping the soa_server1 manually, it appears
the problem is with `"force=true"` - it should be `false="true"`
Truncated debug output...
```
Info: wls_managedserver refresh
Debug: managedserver action: stop
Debug: managedserver action: stop with command
/u01/app/oracle/Middleware/wlserver/common/bin/wlst.sh -skipWLSModuleScanning <<-EOF
connect("weblogic","mydomain","t3://localhost:7001")
shutdown("soa_server1","Server","force=true")
exit()
EOF
^C
Session terminated, killing shell...Notice: Caught INT; storing stop
...killed.
- SNIP -
Ignoring "force=true" and defaulting to false.
Shutting down the server soa_server1 with force=false while connected to
AdminServer ... …
```

Fix forced shutdown bug in wls_managedserver

---

manifests/domain.pp

This needs to happen after the extension template too, (if one is being
used).
Before this change, in my environment, the `nodemanager.properties` file was getting deleted before the extension template was run.  The `Exec["execwlst ${domain_name} extension ${title}"]` would result in a new `nodemanager.properties` being created and with `replace => false` this was never being written with the correct values in `nodemanager.pp`.  In my case, the puppet run would fail because the listenaddress of the node manager was incorrect.

Fix ordering of `rm nodemanager.properties`

---

lib/puppet/provider/wls_managedserver/wls_managedserver.rb
lib/puppet/type/wls_managedserver.rb
manifests/control.pp

New parameter defaults to `false`.  When `true`, changes the protocol
used from `t3` to `t3s`.
Fixes
```
javax.naming.CommunicationException: [Login failed for an unknown reason: P]
```
when trying to start a managed server when ssl is enabled on the admin
server.

Add `adminserver_use_ssl` to `wls_managedserver`

---

README.markdown
lib/puppet/provider/wls_adminserver/wls_adminserver.rb
lib/puppet/provider/wls_ohsserver/wls_ohsserver.rb
lib/puppet/type/wls_adminserver.rb
lib/puppet/type/wls_ohsserver.rb
manifests/control.pp

These changes move control of a OHS Standalone server from wls_adminserver provider to a new one, wls_ohsserver. This was done initially because `adminserver_status` method (https://github.com/biemond/biemond-orawls/blob/master/lib/puppet/provider/wls_adminserver/wls_adminserver.rb#L95) doesn't verify ohs process status, and I think that it's better create a new provider specific to OHS Standalone than put another `if` block.

Create wls ohsserver type

---

.gitignore

Prevents `.DS_Store` files being uploaded to the forge.
https://docs.puppet.com/puppet/latest/reference/modules_publishing.html#set-files-to-be-ignored
This is most noticable when two different modules both have `.DS_Store`
files under the module's `lib` directory.  Plugin-sync flips between the
different copies each time puppet is run.

Add '.DS_Store' to `.gitignore`

---

lib/puppet/provider/wls_exec/wlst.rb
lib/puppet/type/wls_exec/statement.rb

Previous indentation configuration was conflicting with "files/providers/wls_exec/execute.py.erb". For example:
```puppet
wls_exec { "Cluster ${cluster_name} MaxStuckThreadTime":
statement => "@/tmp/MaxStuckThreadTime-${cluster_name}-statement.py",
unless    => "@/tmp/MaxStuckThreadTime-${cluster_name}-unless.py",
}
```
generates python scripts like this:
```python
real_domain='default'
try:
puppet = open("/tmp/wlstScript.out", "w")
print >>puppet, "output" # This is the header for the conversion
try:
cd('/Clusters/EJB_CLUSTER_01/OverloadProtection/EJB_CLUSTER_01/ServerFailureTrigger/EJB_CLUSTER_01')
if cmo.getMaxStuckThreadTime() != 120:
print('MissingMaxStuckThreadTime')
except:
print('MissingMaxStuckThreadTime')
puppet.close()
report_back_success()
except:
report_back_error()
```
This …

Changing indentation from "2" to "4" in wls_exec statements

---

lib/puppet/type/wls_directory_structure.rb

Prior to this commit, the wls_directory_structure type would be
considered present whenever all of the following were present:
- oracle_base_dir
- ora_inventory_dir
- download_dir
But the type also defines two other directories, albeit optionally:
- wls_apps_dir
- wls_domains_dir
These directories weren't checked to make sure they're present, if
defined in the resource itself. From now on, they'll be checked, and if
either of those directories don't exist, they'll be recreated.

wls_directory_structure: absent if domains_dir or apps_dir are absent

---

manifests/weblogic_type.pp

In case there are multiple instances of same version of WLS defined
and installation file for all of them is stored in same directory
there is a need to create just single instance of file resource

Fixing file definition for multiple instances of WLS product

---

files/providers/wls_jdbc_persistence_store/create_modify.py.erb
files/providers/wls_jdbc_persistence_store/index.py.erb
lib/puppet/type/wls_jdbc_persistence_store.rb
lib/puppet/type/wls_jdbc_persistence_store/distribution_policy.rb
lib/puppet/type/wls_jdbc_persistence_store/migration_policy.rb

I've added DistributionPolicy and MigrationPolicy to wls_jdbc_persistence_store. This allows a singleton JMS server to be automatically migrated if the node fails.

Add support for JMS High Availability

---

templates/ohs/domain.py.epp

Starting in 12.2.1, readTemplate() and addTemplate() are deprecated and
both are scheduled to be removed in future releases. Use selectTemplate() and loadTemplates() instead.
loadTemplates() will load all the required templates for the selected template.
The main reason this is needed because when configuring an OHS standalone domain in 12.2.1.2, the module was missing a required template (Basic Standalone System Component Domain). loadTemplates() fixes this issue.
Also JavaHome is now set.

Using selectTemplate/loadTemplates OHS >=12.2.1

---

manifests/packdomain.pp

https://docs.oracle.com/cd/E13179_01/common/docs92/pack/commands.html
-managed={true\|false} | Specifies whether the template is to be used to create Managed Servers on remote machines. The default is false.When this parameter is set to true, a Managed Server template is created that contains a minimal set of files, including SerializedSystemIni.dat,config.xml, and nm_password.properties. It also includes a domain.properties file that is unique to the Managed Server template.Applications and certain application initialization files are not included.The resulting template can be used to create Managed Servers on remote machines.
-- | --

Allow setting pack command option -managed

---

manifests/storeuserconfig.pp

Add an optional parameter "extra_arguments". This parameter can be used to pass extra arguments to storeUserConfig.py command.
This is handy in cases where one would like to add properties such as SSL related.

An optional parameter "extra_arguments" to storeuserconfig.pp

---

files/providers/wls_server/create.py.erb
files/providers/wls_server/index.py.erb
files/providers/wls_server/modify.py.erb
lib/puppet/type/wls_server.rb
lib/puppet/type/wls_server/log_rotationdir.rb

hi @biemond ,
I would like to merge this.  The reason to have this is we have separate file system for logs and if we enable log rotation type, the log rotation dir is set to 'logs/archives' by default which is causing to move the archive logs to different file system. We want all logs to be in the same file system.

add logrotation dir

---

lib/puppet/provider/wls_opatch/prefetching.rb

When executing command using `command` mechanism and command fails no exception is raised. User is responsible to check result for example '$?.exitstatus' and do appropriate action.
Without explicit check after wls_opatch failed puppet task returned success!

fix: raise exception on opatch fail
